### ISSUE TITLE
Setup github actions

### ISSUE THREAD

**Issue by iamniting** [IBM/ibm-storage-odf-operator#11]
We must add below Github actions for testing code basics:
- codespell https://github.com/red-hat-data-services/odf-operator/blob/main/.github/workflows/codespell.yaml
- golangci-lint https://github.com/red-hat-data-services/odf-operator/blob/main/.github/workflows/golangci-lint.yaml
- commitlint https://github.com/red-hat-data-services/odf-operator/blob/main/.github/workflows/commitlint.yaml

**Comment by lbscorpio** [comment]
@iamniting Thanks for your input, I have included them in PR[#13](https://github.com/IBM/ibm-storage-odf-operator/pull/13).
